### ISSUE TITLE
After stealing a weapon(item), the player robbed can still shoot the weapon

### ISSUE THREAD

**Issue by JoaoMorais13** [thelindat/linden_inventory#106]
Hello, you have developed a great inventory and I realy like it! However, me and my friend found a bug that happens when you steal a player.

**To Reproduce :**
In order to see the bug you have to:

1. The player that is going to get robbed needs to have a weapon in his hand.
2. After that the 2nd player uses the /steal command and takes the weapon from him
3. Then the 2nd players has a new weapon in the inventory and the player that got robbed stil has the weapon in his model's hand but not in the inventory
4. The player that got robbed can shoot a weapon even tho he hasn't any weapon in his inventory

**Expected behavior :**
I was expecting to clear the player's model hand after geting robbed.

**Video footage :**
[Here you have a video showing](https://youtu.be/h6fag5YKRKI)

**Additional context :**
Btw, every time I say •weapon' I'm refering to the item that is working as a weapon.

**Thank you** 👍

**Comment by thelindat** [comment]
Fixed.

**Comment by JoaoMorais13** [comment]
Awesome! Great work!
