### ISSUE TITLE
Add quick movement

### ISSUE THREAD

**Issue by Olvidate** [thelindat/linden_inventory#11]
Hello, **Lindat**.

I like so much your inventory, but I think it lacks a bit of speed when it comes to moving objects, therefore I suggest adding a quick movement with the right-click.

It basically consists on pressing the right click and automatically moving to the right inventory, as stores do.

**Comment by thelindat** [comment]
Quick movement is planned but not compatible with the current server setup (need to change item validation and transferring).
If the UI is lagging, disable `Windows Game Mode` and enable the FiveM setting `NUI in-process GPU`

**Comment by Olvidate** [comment]
I was referring to the slowness of moving items, it would be good to see it, we will have to wait, thanks for responding so quickly!

**Comment by kFxDaKing** [comment]
+1

**Comment by thelindat** [comment]
Done for next release.
