### ISSUE TITLE
es_extended doesn't function correctly when using linden_inventory

### ISSUE THREAD

**Issue by amr-coding** [thelindat/linden_inventory#119]
**Describe the bug**

[  script:es_extended] SCRIPT ERROR: @es_extended/server/commands.lua:25: attempt to index a boolean value (local 'xPlayer')
[  script:es_extended] > cb (@es_extended/server/commands.lua:25)
[  script:es_extended] > ref (@es_extended/server/functions.lua:130)

I followed everything the documentation explained to install the script, downloaded the dependences also but one thing I notice is when I start the linden_inventory script some other scripts like chat does not function correctly, I'm not sure why but it seems that the es_extended doesn't function correctly also, but when I'm in the server and I restart es_extended the linden_inventory script works.

Before using the script I created charater, but once I started the inventory script and spawned the character gets changed to the default fivem character, when using /char it doesn't show anything.

I wrote ensure linden_inventory at the end of the script and also I installed all the other dependences.

I'm using your fork of es_extended and I put it in the [ESX] folder.
Also when I try to press K inside or outside the vehicle it says you can't open inventory now.

**To Reproduce**
1. Join the server
2. Click on F2
3. Nothing happens 

**Expected behavior**
I'm expecting the inventory to show up and doesn't effect es_extended cause it seems that when I run linden inventory script the es_extended gets missed up.
**Screenshots**

**Additional context**

**Comment by thelindat** [comment]
At the very least it sounds like you're using basic-gamemode (or starting something that has it as a dependency).
![image](https://user-images.githubusercontent.com/65407488/121610862-51bc4780-ca9a-11eb-9130-234a21cae520.png)

if xPlayer is a boolean then it means your xPlayer doesn't exist - I assume because of the conflict being caused.

**Comment by amr-coding** [comment]
Thanks for responding, I removed the resources that can result in errors but still the same problem occur.


I'll share the server.cfg with you to make sure that the order of starting each resource is correct.

##########################################################################
set mysql_connection_string "mysql://root@localhost/PlumeESX_C13287?charset=utf8mb4"
set onesync legacy
set sv_enforceGameBuild 2060
## These resources will start by default.
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure hardcap
ensure default_spawnpoint

## Add system admins


## ESX v1-final Stuff
ensure es_extended
ensure mysql-async
ensure ghmattimysql
ensure cron
ensure instance
ensure skinchanger
ensure es_extended
ensure esx_menu_default
ensure esx_menu_dialog
ensure esx_menu_list
ensure esx_datastore
ensure esx_identity
ensure esx_skin
ensure esx_status
ensure esx_basicneeds
ensure esx_billing
ensure esx_addoninventory
ensure esx_addonaccount
ensure esx_society
ensure esx_license
ensure esx_service
ensure esx_garage
ensure esx_vehicleshop
ensure esx_jobs
ensure esx_joblisting
ensure esx_policejob
ensure esx_ambulancejob
ensure esx_mechanicjob
ensure esx_taxijob
ensure esx_lscustom
ensure esx_atm
ensure esx_shops
ensure esx_weaponshop
ensure esx_clotheshop
ensure esx_barbershop
ensure esx_drugs
ensure esx_holdup
##ensure linden_inventory
add_ace resource.es_extended command.add_ace allow
add_ace resource.es_extended command.add_principal allow
add_ace resource.es_extended command.remove_principal allow
add_ace resource.es_extended command.stop allow

## Extra stuff
ensure bob74_ipl
##ensure esx_adminplus
ensure gcphone
ensure Kl_HudV2
ensure loadingscreen
ensure simpledrift
start LegacyFuel
start meta_libs
start mythic_notify
start mhacking
start doors
start [motel]
start esx_motel
start mythic_progbar
ensure linden_inventory	
#######################################################################

**Comment by thelindat** [comment]
Get rid of that `ensure default_spawnpoint` crap from plume

**Comment by amr-coding** [comment]
Okay, after some of the trail and error I found that linden fork of es_extended causes the problem.
I installed fresh server and I started to install the dependences [ Not the inventory script itself ] required for the inventory one by one, I found that everything work just fine except the fork of es_extended made by you.

However I made a backup of the Legacy version of es_extended and once I replaced your fork of es_extended with the Legacy version, the server worked.
When I installed the es_extended forked by you the server won't complete loading scripts and stops at point of loading "awaiting scripts".
I will try to edit the legacy version by the code mentioned in documentation and see if the problem gets solved, anyways if you there is something needed to be done let me know please.
Thanks!

**Comment by amr-coding** [comment]
**Update:**
After I installed the latest version of the inventory 1.7.0 it worked like a charm and I reinstalled the es_extended fork everything seems to work just fine.
Thanks for your efforts so much!
