### ISSUE TITLE
Weapons can not be reloaded

### ISSUE THREAD

**Issue by xrtw** [thelindat/linden_inventory#1199]
Sadly, no errors on client or server side. Ammos are the same, weapons the same. Just updated to the newest version

Error below appears when using item like bread, it uses 2 times.
https://i.gyazo.com/f32972a516b66028ce00218cf6356c9f.png

**Comment by thelindat** [comment]
Nothing changed on ammo use or item use in general. Make sure you merged changes correctly and refreshed fxmanifest.
