### ISSUE TITLE
bad argument #1 to 'pairs' Error

### ISSUE THREAD

**Issue by X00LA** [thelindat/linden_inventory#121]
**Describe the bug**
I get this error when starting my server:

[script:linden_invent] SCRIPT ERROR: @linden_inventory/server/main.lua:60: bad argument #1 to 'pairs' (table expected, got nil)
[script:linden_invent] > fn (@linden_inventory/server/main.lua:60)

**To Reproduce**
Got this error since installed 1.7.0 and 1.7.1 of linden_inventory.
With 1.6.4 this error wasnt showing.

Forgot to mention that it is impossible now to join the server because linden_inventory isnt loading.
Get message:
Connection rejected by server: Inventory system has not yet loaded

**Comment by thelindat** [comment]
You need to update your files. If you keep shared/items so you can convert, you still need to get shared/weapons

**Comment by X00LA** [comment]
I have completely deleted the old files and uploaded the files which come with the package.
So the inventory is installed as provided.

**Comment by X00LA** [comment]
Found the error!

It was a misspelling in the /shared/items.lua which comes completely from my side.
Think my cat tipped a key when i was looking over the files and placed a letter where nothing should be placed. ( Those cats! :/ )
Interesting part is, that the file was not showing up in console or logs with an error.
Found it only because I was checking all files if there could be an issue in it.

Sorry for the false alarm.
