### ISSUE TITLE
Some error about validation 

### ISSUE THREAD

**Issue by boringwolf** [thelindat/linden_inventory#124]
**Describe the bug**
1. [script:linden_invent] SCRIPT ERROR: @linden_inventory/server/main.lua:724: attempt to index a nil value (field '?')
2. [script:linden_invent] SCRIPT ERROR: @linden_inventory/server/main.lua:756: attempt to index a nil value (field '?')
3. [18] boringwolf failed item validation (type: freeslot, fromSlot: nil, toSlot: nil, fromItem: table: 0x7f695bb32df0, toItem: table: 0x7f695bb32df0, reason: source slot is empty)

**To Reproduce**
1. Go to open a stash open by this way: exports['linden_inventory']:OpenStash({name = property.name, label = property.label, owner = owner, slots = 200})
2. I move a random item into the stash. And move them in stash without switch to player inventory.
3. I see the error one and error two.
4. and after I see error one and two, I move my item back to my inventory.
5. I got error 3

**Comment by thelindat** [comment]
Screenshot your database table structure for the inventory. Should look like
![image](https://user-images.githubusercontent.com/65407488/122020203-e959c700-ce07-11eb-8c98-f70e0d36d87a.png)

**Comment by boringwolf** [comment]
![unknown (2)](https://user-images.githubusercontent.com/16619016/122046454-7f461f80-ce11-11eb-84cd-1e96f9e44146.png)

**Comment by boringwolf** [comment]
![image](https://user-images.githubusercontent.com/16619016/122082967-0657bf80-ce33-11eb-92f1-d127297e682f.png)
oh sorry I paste wrong one.

**Comment by boringwolf** [comment]
I found the error is because of the server/main.lua line 325 and line 330, type need to be change into invType.
and I think line 367 same wrong too?

**Comment by boringwolf** [comment]
#125 
I think this can fix it.
