### ISSUE TITLE
Arithmetic On A Nil Value Field count

### ISSUE THREAD

**Issue by ProjectRogueRP** [thelindat/linden_inventory#127]
**Describe the bug**
We keep getting these errors for count where the error in the clients F8 Console is:
linden_inventory/client/main.lua:311 attempt to perform arithmetic on a nil value (field 'count') which will stop the resoruce from time to time. We are unsure why it keeps happening or throwing this error. We are using it as follows:

RegisterNetEvent('rogue_dd:illegaltablet')
AddEventHandler('rogue_dd:illegaltablet',function()
local ped = GetPlayerPed(-1)
local inventory = ESX.GetPlayerData().inventory
local pcase = 0
local circuit = 0
local copper = 0
local uncut_rubbies = 0
local ipad = 0
local oldphone = 0
    for i=1, #inventory, 1 do
        if inventory[i].name == 'plasticcase' then
            pcase = inventory[i].count
        end

We have always used it like this with no errors, but with this inventory we are getting these errors constantly. Any ideas to get this to stop happening?

**To Reproduce**
Event above will throw the error

**Expected behavior**
For the error to not happen and get the count correctly

**Screenshots**
https://i.imgur.com/5z0Ax9Q.png

**Comment by thelindat** [comment]
Line 311 doesn't seem to match up with anything, but the closest reference to count is itemNotify - which the above code does not call.
