### ISSUE TITLE
BT-Target Error

### ISSUE THREAD

**Issue by Daemonns** [thelindat/linden_inventory#130]
**Describe the bug**
Bt-target Data error when going to store

**Screenshots**
![1111](https://user-images.githubusercontent.com/81875858/122357434-55623980-cf86-11eb-8ab2-bde569b70c1e.PNG)

**Comment by thelindat** [comment]
I haven't played with bt-target at all, but I believe you need the forked version to pass data through.
https://github.com/OfficialNoms/bt-target

**Comment by Pratyok** [comment]
how to make bt target work? I've used this version of bt target https://github.com/OfficialNoms/bt-target

preview https://streamable.com/3i453z

**Comment by thelindat** [comment]
Check discord snippets or ask for help there; I haven’t played with bttarget so my experience is limited
