### ISSUE TITLE
Guns/Hotbar stuck

### ISSUE THREAD

**Issue by d3rp-jsx** [thelindat/linden_inventory#132]
**Describe the bug**
Randomly I can't holster or switch my guns in hotbar, I can't understand why, no errors at all, I can just restart the resource.

**To Reproduce**
Seems random, I can't reproduce

**Expected behavior**
I should be able to holster or switch guns everytime

**Comment by ScaredDonut** [comment]
I've only had this issue when I restarted the resource while the server is on had to restart the resource again to fix it. 

But you run the risk of losing inventory items if you restart it while players are on.

**Comment by thelindat** [comment]
Fixed.
