### ISSUE TITLE
gun stuck

### ISSUE THREAD

**Issue by maxcamorra** [thelindat/linden_inventory#133]
**Describe the bug**
putting on weapon attachements causing the the weapons etc. to get stuck, you can't holster them anymore or use anything in the inventory

using 1.7.3

**To Reproduce**
1. take out weapon for example pistol
2. put extended pistol clip on use
3. weapons get stuck and cant get back holstered, you have to restart the game...
4. no error in console or f8 but still an error which can get reproduced by all our players

**Expected behavior**
attachments should get on the weapon and you should be able to holster and take out the weapons.

**Comment by thelindat** [comment]
Fixed.
