### ISSUE TITLE
Inventory broken after 1.7.4

### ISSUE THREAD

**Issue by X00LA** [thelindat/linden_inventory#134]
**Describe the bug**
After the update to 1.7.4 the inventory is completely broken.
Inventory only opens once. After that the animations plays but the inventory keeps closed.
Can't buy anything in stores.
Can't use anything.
No money, black_money shows up in inventory.

**To Reproduce**
1. Installed fresh linden_inventory 1.7.4 (with latest es_extended_legacy (linden) and latest esx_multichar (linden)
2. Start server and join.
3. Go to shop or open inventory.
4. See problem

**Screenshots**
here's a short video to show you what I mean.
https://youtu.be/B_90jnAcsLg

**Comment by X00LA** [comment]
I fiddled a bit around and found some interesting things.
After I deleted my char and all related entries in the db the inventory begun to work again.
I tested also if bt-target would now work, but no.
After deactivating bt-target my complete inventory included all money and black money are deleted completely. Also from the db.
I think the whole problem evolves around bt-target. something smells fishy here.

**Comment by thelindat** [comment]
If you restarted inventory when disabling bttarget you need to save first. I removed the auto save on resourcestop because it often overwrote inventories with nil data

**Comment by X00LA** [comment]
Saving when its broken is not that easy, luckily it is my dev server where I play around so no harm done.
Looked over the implemented code for bt-target and for my coding beginner eye it looks good, but somewhere must be an issue with it.

When the inventory is started without bt-target and you have the coordinates for it in the shop coords they wont show up. You have to delete and reinsert them every time you switch. This is a bit annoying.

I will test bt-target some more with the examples on the repo to see if it's the code or bt-target itself.
Unfortunately the next two days i have very long shifts at work (12h) so not that much time to do that until monday.

Maybe the creator of the pulled code should look over it again. Maybe this would help to fix this problems. Definetly worth a try since everyone seems to have problems with bt-target.

**Comment by braydxnn** [comment]
Same issue for me

**Comment by X00LA** [comment]
> Same issue for me, I am not using bt-target but money is not appearing in my inventory and it seems sometimes my inventory just randomly stops opening? Same with hotbar.

Try the same as in my second post. It may work again without any problems.

**Comment by thelindat** [comment]
Pending some sort of report on repro.

**Comment by X00LA** [comment]
Problems should be solved now with my newest commit. Tested various settings and no problems at all. Cant reproduce the issues that I had with bugged bt-target.
