### ISSUE TITLE
Weight Update + Error on join

### ISSUE THREAD

**Issue by Arliind** [thelindat/linden_inventory#140]
I just updated to the latest commit at the time of writing this. On join, I get this error on client side console:
![FiveM_b2189_GTAProcess_nEMupjzVUm](https://user-images.githubusercontent.com/35179943/122685796-99af3d00-d205-11eb-9a0d-41f9ce4419de.png)

This is the line it is  referring to inside shared/weapons:
`else Items[k].server, Items[k].client.consume = nil, nil end`

Also another small visual bug, when buying something from a shop, it doesnt update the visual inventory weight so it will still show as 0 kg until you back out and open your inventory. It still updates the weight so they cant go over the max but it doesnt update it visually.

**Comment by Arliind** [comment]
![FiveM_b2189_GTAProcess_xjpsthKPMN](https://user-images.githubusercontent.com/35179943/122689292-74c4c500-d219-11eb-97eb-0ce15acc4c2f.png)
I am also getting this when I am trying to take out a weapon.

This is the line it is referring to inside client/main:
`if Items[item.name].throwable then item.throwable, item.metadata.ammo = 1, true end`

I am also having issues using `TriggerEvent('linden_inventory:busy', true)`. This is not setting players as busy. Im using your version of progbar with the inventory edits and it is still not setting people as busy when the progbar is active.

**Comment by thelindat** [comment]
Fixed.
