### ISSUE TITLE
When upgrading to the latest version, I cannot shoot the stungun (taser)

### ISSUE THREAD

**Issue by Okkie-NL** [thelindat/linden_inventory#141]
**Describe the bug**
I updated from 1.6.4 to the latest version on Github (Code Download from yesterday) and now can no longer shoot the stungun (taser).

**To Reproduce**
Just spawn in the stungun with /giveitem and it does not work.

**Expected behavior**
The stungun shoots.

Is anyone seeing the same behavior. Thanks in advance.

**Comment by Okkie-NL** [comment]
Tested it today with a fresh install. Same issue.

**Comment by Okkie-NL** [comment]
This seems to solve the issue temporary, but probably not the correct solution ;)
![image](https://user-images.githubusercontent.com/10367379/122749676-e50d2e00-d28d-11eb-82fe-d4b3a481151f.png)

**Comment by thelindat** [comment]
Doesn't happen to me? Stungun doesn't even use ammo in the base game.

**Comment by Arliind** [comment]
I can confirm that this is also happening with me after a fresh install of the inventory.

**Comment by thelindat** [comment]
This was apparently related to fivem's buggy new native to disable auto reload, which I removed the other day.
