### ISSUE TITLE
Ammo bug

### ISSUE THREAD

**Issue by kFxDaKing** [thelindat/linden_inventory#148]
**Describe the bug**
There is bug with ammo, here is video:
https://streamable.com/7syo2q

**To Reproduce**
Reload gun to some ammo, for example 30, shoot few times, holster weapon and your ammo is back to previous number.

No errors.

I think it should be saved when u holster gun, also it should be saved on reload, and anytime, when other script set your current weapon to unarmed.

**Comment by kFxDaKing** [comment]
Another video, that shows another problem with ammo:

https://streamable.com/hbo3p3

in client/main.lua im printing this:
![image](https://user-images.githubusercontent.com/52855882/123544461-ab3b9c00-d753-11eb-9aa1-d62ad47f9020.png)

**Comment by kFxDaKing** [comment]
Looks like that 60 ammo in print is max. ammo of that weapon?

**Comment by thelindat** [comment]
It's fixed.

**Comment by kFxDaKing** [comment]
uhm, where its fixed? I cant see commit for it.
