### ISSUE TITLE
Bug while dragging

### ISSUE THREAD

**Issue by kFxDaKing** [thelindat/linden_inventory#149]
**Describe the bug**
When you drag weapon on another weapon in hotbar, it breaks.
You cant use inventory anymore, untill script restart.

**To Reproduce**
1. Get 2 weapons in inventory, put 1 in hotbar.
2. Drag 1 weapon on the image of 2nd gun in hotbar, and it breaks.

EDIT: Weapon must be broken, 0 durability.

Video:

https://streamable.com/lc3n6d

**Comment by Arliind** [comment]
I have been able to reproduce this kinda. I can still fully use my inventory but the broken pistol can not be moved. If you try and move it then it will stay in that inventory slot and wont drag when you try again after the initial time whether or you have closed your inventory or not. Everything else in the inventory can be used.

**Comment by Arliind** [comment]
https://i.imgur.com/jYBBIOj.png

You get this when you the broken gun onto another gun, vice versa.

**Comment by thelindat** [comment]
https://github.com/thelindat/linden_inventory/commit/0d254ee2de6fc7dd57d90451f666c1165d5ea0f0

See if that fixes it

**Comment by Arliind** [comment]
> [0d254ee](https://github.com/thelindat/linden_inventory/commit/0d254ee2de6fc7dd57d90451f666c1165d5ea0f0)
> 
> See if that fixes it

Nope did not fix it

**Comment by Arliind** [comment]
still getting that error from above, https://i.imgur.com/YfX8oHK.png

**Comment by Arliind** [comment]
In Addition to this, the commit you done before 0d254ee breaks durability on weapons and it'll always stay at 100%.

**Comment by thelindat** [comment]
Fixed.
