### ISSUE TITLE
MYSQL ERROR

### ISSUE THREAD

**Issue by molcik-dev** [thelindat/linden_inventory#15]
![image](https://user-images.githubusercontent.com/59299731/115122617-1f6dfc80-9fb9-11eb-82ce-4422bd05795c.png)

mysql error, idk how can I fix it

**Comment by Trey2k** [comment]
Try removing the If not exists from the alter table statement, I remember I had to do this to get it working. It may be due to different MySQL versions i am unsure. But on my version it was improper syntax

**Comment by molcik-dev** [comment]
![image](https://user-images.githubusercontent.com/59299731/115130569-0123f300-9ff1-11eb-9b31-156211f3d034.png)
I have error here

**Comment by molcik-dev** [comment]
@Trey2k

**Comment by Trey2k** [comment]
Unsure, works for me. What MySQL version are you running?

**Comment by molcik-dev** [comment]
I have PHPmyAdmin

**Comment by molcik-dev** [comment]
send me your updated files.sql file
Or we can go to Discord, this better of this

**Comment by Trey2k** [comment]
What is your MySQL server version though

**Comment by molcik-dev** [comment]
idk?

**Comment by thelindat** [comment]
You don't need to run the alter table part if it's your first time setup.

Just manually add the tables if you can't run the file that works for others.

**Comment by molcik-dev** [comment]
ok...
