### ISSUE TITLE
item in drop nothing moveable anymore

### ISSUE THREAD

**Issue by maxcamorra** [thelindat/linden_inventory#151]
**Describe the bug**
When I put an item into the drop its not moveable then anymore.

**To Reproduce**
1. Put item into drop

**Expected behavior**
Drop should be created and the items should be moveable.

**Screenshots**
![image](https://user-images.githubusercontent.com/78707245/123555779-26b74080-d788-11eb-9ffb-16d71745e756.png)

**Comment by thelindat** [comment]
Much like 90% of the bugs you report, cannot reproduce.

![image](https://user-images.githubusercontent.com/65407488/123563830-3a9b8a80-d7fa-11eb-9130-ed818de435af.png)
![image](https://user-images.githubusercontent.com/65407488/123563832-3f603e80-d7fa-11eb-8715-b98a2faeaf62.png)
![image](https://user-images.githubusercontent.com/65407488/123563843-45eeb600-d7fa-11eb-9c3f-5a4abe19cfe0.png)

**Comment by maxcamorra** [comment]
hmm ok
