### ISSUE TITLE
Issue with loot weight

### ISSUE THREAD

**Issue by X00LA** [thelindat/linden_inventory#152]
**Describe the bug**
I have configured some items as loot for the cars, spare wheel and repairkit.

```
['repairkit'] = {trunk = 100, glovebox = 0, dumpster = 0, min = 1, max = 1,},
['tyrekit'] = {trunk = 100, glovebox = 0, dumpster = 0, min = 1, max = 1,},
```

Both are also defined in shared/items.lua.

```
['repairkit'] = {
  label = 'Bordwerkzeug',
  weight = 2500,
  stack = true,
  close = true,
  client = {
      consume = 0,
      usetime = 1,
      event = 'esx_repairkit:onUse'
  }
},

['tyrekit'] = {
  label = 'Ersatzrad',
  weight = 3500,
  stack = false,
  close = true,
  client = {
    consume = 0,
    usetime = 1,
    event = 'tyrekit:onUse'
  }
},
```

The repairkit works without a problem, but the tyrekit shows in weight (NaNg). ![Screenshot](https://i.imgur.com/ubvTor6.png)

**To Reproduce**

**Expected behavior**
I also have it in a shop, ![Screen](https://i.imgur.com/ZHHtk5P.png), and when i bought it it works and had proper weight ![Screen](https://i.imgur.com/gN7z4uL.png).

**Screenshots**

**Additional context**
I looked over my settings and everything looks ok. (Since the tyrekit works when bought everything should be alright from my side.)

**Comment by thelindat** [comment]
Fixed.
