### ISSUE TITLE
better stacking

### ISSUE THREAD

**Issue by Meteiou** [thelindat/linden_inventory#153]
**Is your feature request related to a problem? Please describe.**
Better stacking. You want put $1000 from your inv to your stash where u have $2000, u need to put it on single slot and the u need to drop it on money in stash, why?

**Describe the solution you'd like**
This little code fix it, but its by me XD

`} else if (count < fromItem.count && fromItem.name == toItem.name && toItem.stack && is_table_equal(toItem.metadata, fromItem.metadata)) { // stack
					let toCount = Number(toItem.count)
					let newcount = (Number(count)+toCount)
					let newDataItem = {}
					let oldslotCount = fromItem.count - count
    				oldItemData = {}
    				oldItemData.count = Number(oldslotCount)
    				oldItemData.name = fromItem.name
    				oldItemData.label = fromItem.label
    				oldItemData.stack = fromItem.stack
    				oldItemData.description = fromItem.description
    				oldItemData.metadata = fromItem.metadata
    				oldItemData.weight = fromItem.weight
    				oldItemData.slot = fromSlot
    				oldItemData.price = fromItem.price
					newDataItem.name = toItem.name
					newDataItem.label = toItem.label
					newDataItem.count = Number(newcount)
					newDataItem.metadata = toItem.metadata
					newDataItem.stack = toItem.stack
					newDataItem.description = toItem.description
					newDataItem.weight = toItem.weight
					newDataItem.price = toItem.price
					toInventory.find("[inventory-slot="+toSlot+"]").html('<div class="item-slot-img"><img src="images/'+toimage+'.png'+'" alt="'+toItem.name+'" /></div><div class="item-slot-count"><p>'+numberFormat(newcount, toItem.name)+' '+weightFormat(toItem.weight/1000 * newcount)+'</p></div><p><div class="item-slot-label">'+toItem.label+'</div>');
					toInventory.find("[inventory-slot="+toSlot+"]").data("ItemData", newDataItem);
					fromInventory.find("[inventory-slot="+fromSlot+"]").html('<div class="item-slot-img"><img src="images/'+fromimage+'.png'+'" alt="'+oldItemData.name+'" /></div><div class="item-slot-count"><p>'+numberFormat(oldItemData.count, oldItemData.name)+' '+weightFormat(oldItemData.weight/1000 * oldItemData.count)+'</p></div><div class="item-slot-label">'+oldItemData.label+'</div>');
    				fromInventory.find("[inventory-slot="+fromSlot+"]").data("ItemData", oldItemData);
					$.post("https://linden_inventory/saveinventorydata", JSON.stringify({
						type: "split",
						frominv: inv,
						toinv: inv2,
						fromSlot: fromSlot,
						toSlot: toSlot,
						oldslotItem: oldItemData,
        				newslotItem: newDataItem,
						invid: toinvId,
						invid2 :toinvId2
					}));
					success = true`

**Comment by thelindat** [comment]
Implemented with some tweaks.
