### ISSUE TITLE
Error with inventory

### ISSUE THREAD

**Issue by hugochugo** [thelindat/linden_inventory#156]
![image](https://user-images.githubusercontent.com/66925703/123571304-f24b8080-d797-11eb-866c-dc9d467bad2a.png)

First time using your inventory everything seems to be installed correctly using all your resources from your esx-legacy page. When I connect I can only open the inventory once and also cant see any stores, when I restart the resource everything works fine if I relog it will not work again. Image is the error I get when I choose my character without trying to do anything, no errors server side. Using your multi-character idk if it has anything to do with it?

**Comment by thelindat** [comment]
My repo with all esx resources isn’t compatible with the inventory. Firstly the repo is still being updated and secondly the inventory requires a modified version of esx
