### ISSUE TITLE
Ammo bug + Metadata description bug + Weapon request

### ISSUE THREAD

**Issue by czsquizer** [thelindat/linden_inventory#157]
Hello Lindat,
I am now on my server setting up the inventory, but I have found some things that could be cool to think about.
Thank you for reading this and thank you for your time spent on this project and with me helping me solving the problems.

**1.**
- This bug is when you shoot out ammo, you hide and take the weapon, you will get the ammo back to 1.
- I have found a video from another user on the Discord server
- Video: https://streamable.com/3umpu6

**2.**
- When a description (meta description) is too long, it actually covers the text
- 
![lPFF8QpW4r](https://user-images.githubusercontent.com/56487372/123707068-6e61c900-d869-11eb-89f1-87517e36c48c.png)

**3.**
- When you have 2 weapons in hotbar (for example 1. is Pistol, second is AK)
- When you have weapon in hand (the slot 1(pistol)) and you press 2 to take the AK out, the pistol gets holstered, but AK does not go out

**4.** 
- This is not a bug, but it is a feature request.
- Add possibility to define if the weapon can be pulled out of in the car
- Now you can take out an AK for example in the car, but you can not shoot for it

**5.**
- For the documentation it would be nice to add a notice that if you convert from other inventory, you also need to add money as an item to the inventory in count of as you have money
- For example, if you have 567$ cash, you need to add money item in count of 567 to the inventory while converting using the server/convert.lua otherwise the money on your connect will be set to 0

**6.**
- When I try to put 150$ to stash, it works fine, but when I try to put more 250$ to the same slot, it gives me error that I can not perform that action (works with every amount of money)

**7.**
- I think there is missing setJob event, for example for the shops
- When you change the job there will be issues with the job shops

**Comment by czsquizer** [comment]
+
6.
- When I try to put 150$ to stash, it works fine, but when I try to put more 250$ to the same slot, it gives me error that I can not perform that action (works with every amount of money)

**Comment by thelindat** [comment]
1 and 3 are fixed.

6 is due to an issue with item stacking that's persisted from the original code.

7 is not a bug - ESX Legacy imports remove the need for setJob

**Comment by czsquizer** [comment]
Okey, than you.
