### ISSUE TITLE
Inventory Freezes

### ISSUE THREAD

**Issue by RKMMods** [thelindat/linden_inventory#161]
Sometimes during our RP's the inventory just freezes with guns and we need to restart the script. This also happens sometimes when reloading weapons.

**Comment by Ruqen** [comment]
More info plz, freezes means nothing

**Comment by RKMMods** [comment]
Basically it makes it so you can't use the inventory at all and you can't pull out any guns/items

**Comment by Arliind** [comment]
Can not reproduce this. make sure you're running the latest version of Linden Inventory with the edits required for ESX Legacy. Also show any errors, screenshots etc of the issue you're having.

**Comment by thelindat** [comment]
There was an issue reported with auto reload set to true, see if that is
the problem you’re having

**Comment by thelindat** [comment]
Can't reproduce
