### ISSUE TITLE
while giving items to player u can add their steam names or character names so items will be given to specific players if many people stand near the particular person

### ISSUE THREAD

**Issue by muthurockon** [thelindat/linden_inventory#163]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Arliind** [comment]
How would you stop the ability to metagame if this was to be added? People could go around, go next to people, drag something into give and it'll tell them the persons character name without getting to know them... I do believe there was a conversation about this a while ago and this was one of the reasons that this idea hasnt been implemented. Someone correct me if im wrong though.

**Comment by redacid95** [comment]
I personally wanna upvote this suggestion. The meta ability is somewhat limited. This is a huge quality of life, and will allow for easier giving to people. People can easily tell if someone knows their name from meta information, and if they can't, then I don't think they care enough about their story.

**Comment by Senlar** [comment]
Just use server ID. If all you show is server ID they can't easily meta that to a person as the server ID changes each login.

**Comment by thelindat** [comment]
I believe somebody posted something on the discord for server ids. I'll take a look at it later and make it a config option.

**Comment by redacid95** [comment]
> I believe somebody posted something on the discord for server ids. I'll take a look at it later and make it a config option.

Yes, I did. Here is the message link. https://discord.com/channels/813030955598086174/816673612621938759/862021800166817833

**Comment by Senlar** [comment]
If there's only one other player nearby then it shouldn't be needed, only if multiple players are around should it popup a list to choose an ID.
