### ISSUE TITLE
Could not find dependency ghmattimysql for resource linden_inventory

### ISSUE THREAD

**Issue by Squizy1722** [thelindat/linden_inventory#164]
![4b0e9797e7e1e0a466bfd268dd0a7866](https://user-images.githubusercontent.com/86523689/124386881-1c93c580-dce5-11eb-8fa1-6f26fb39b2f3.png)

**Comment by Arliind** [comment]
How is this a bug?

**Comment by Arliind** [comment]
Please read what it says.
