### ISSUE TITLE
If you remove an item from the inventory in the car and then pick it up again, it will not work

### ISSUE THREAD

**Issue by InLoveWithLua** [thelindat/linden_inventory#167]
**Describe the bug**

If you remove an item from the inventory in the car and then pick it up again, it will not work

**To Reproduce**

Go in any car. Throw something out of your inventory. Pull it back in.  (Throw it out again and the inventory will close by itself and you will get an Script error in console .)  Now Close your inventory and open again. The Item is not in your inventory. (You will also get a script error)

**Expected behavior**

The item should be back in the inventory

**Screenshots**
![22](https://user-images.githubusercontent.com/75123219/124957410-58969580-e019-11eb-8ee8-40162254b304.PNG)

**Comment by thelindat** [comment]
The actual bug here is the drop opening; it shouldn't open if you are in a vehicle.

If you get out of the vehicle you can grab the item.
