### ISSUE TITLE
Weapon camos are duplicated on weapons

### ISSUE THREAD

**Issue by InLoveWithLua** [thelindat/linden_inventory#168]
**Describe the bug**

Weapon camos are duplicated on weapons

**To Reproduce**
1. Pack an advanced and a pistol in your inventory
2. Buy a luxury and a zebra camouflage (or something else)
3. Put the Luxury camo on your advanced
4. put your Pistol out and put Zebra (or other) camo on it. Nothig Happens.
5. holster pistol an pull it out again. You now have a Luxury Camo on your Pistol and your Zebra camo is gone
6. Put any other Camo on your Pistol and it will show components: Luxury_camo, Luxury_Camo

**Expected behavior**

The new skin should appear on the pistol just like the first weapon

**Comment by thelindat** [comment]
Camo falls under components, and the system in place is incredibly basic (use item, add metadata to item).
Parts of it need a rewrite and need moving to the server for security purposes. When I get around to this, I cannot guarantee full compatibility with existing components (we'll see).

**Comment by RobiZona** [comment]
I fixed this problem that the camos and other components are not loaded, I rewrote all the weapon.lua file in shared, the only problem that remains is in the description of the weapon, a new component is added every time and that is not removed old, so the description will become very long
if you give me permission I share the rewritten weapon.lua file
