### ISSUE TITLE
New Es_extended and inventory

### ISSUE THREAD

**Issue by JoshSmith1295** [thelindat/linden_inventory#169]
When you die with new es_extended and inventory you get stuck in this weird thing where you cant distress signal and does give you like a black screen

![](https://cdn.discordapp.com/attachments/403231444018659330/862760953686917130/unknown.png)

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/124984154-35e99880-e07c-11eb-8987-82eee3d437e2.png)
🙃
