### ISSUE TITLE
Black Money not syncing properly between players & secondary inventory

### ISSUE THREAD

**Issue by WasabiRobby** [thelindat/linden_inventory#171]
**To Reproduce**
Basically what is happening is that any black money you try and store will be removed and the amount of regular money you have on hand will be added in black as well.

**Video**
https://streamable.com/orm752

**Additional Information**
Was fine before latest ESX Legacy/Inventory update

**Comment by thelindat** [comment]
Issue was related to the new `syncInventory` xPlayer function - dirty money count was being set to match money.

Update ESX to resolve.

**Comment by maxcamorra** [comment]
> Issue was related to the new `syncInventory` xPlayer function - dirty money count was being set to match money.
> 
> Update ESX to resolve.

same issue for me. I updated the ESX aswell but it doesn't work, also when I give black_money to the people it just get removed again.

**Comment by thelindat** [comment]
> 
> 
> > Issue was related to the new `syncInventory` xPlayer function - dirty money count was being set to match money.
> > Update ESX to resolve.
> 
> same issue for me. I updated the ESX aswell but it doesn't work, it just get removed from the player

I can assure you that it is fixed, and if you're having the issue then you did not download the update.
