### ISSUE TITLE
Not working ESX.PlayerData

### ISSUE THREAD

**Issue by Daemonns** [thelindat/linden_inventory#174]
**Describe the bug**
in qrp_idcards 

  local metadata = ESX.GetPlayerData().inventory[item.slot].metadata
![C222](https://user-images.githubusercontent.com/81875858/125195179-25593e00-e287-11eb-84bd-17c912a50a61.PNG)

**Comment by Daemonns** [comment]
its ok now nvm

**Comment by Apolo-sys** [comment]
Its not linden error, the value "item" its nil
