### ISSUE TITLE
CANT ACCESS INVENTORY WHEN CUFFING

### ISSUE THREAD

**Issue by ProjectRogueRP** [thelindat/linden_inventory#177]
**Describe the bug**
I cuff people via our Police Jobs, and when cuffing people soft or hard, it breaks the inventory. We have to cuff again, and then it lets us access our inventory again. Anyway to fix this? Its super annoying!

**To Reproduce**
Cuff someone hard or soft, and then try to access your inventory

**Expected behavior**
To be able to use inventory after cuffing without having to double cuff

**Comment by thelindat** [comment]
The hell events are you triggering when you cuff, because they should only set on the one being cuffed. This isn't a default issue.
