### ISSUE TITLE
Limit items stacked each slot

### ISSUE THREAD

**Issue by Apolo-sys** [thelindat/linden_inventory#180]
**Is your feature request related to a problem? Please describe.**
No, only suggestion 👍 

**Describe the solution you'd like**
Make an option for limit the items stacked each slot.

An extra option when creating new item 

Code Example: 

`
	['burger'] = {
		label = 'Burger',
		weight = 220,
		stack = true,
                maxStackEachSlot = 32,
		close = true,
		client = {
			status = { hunger = 200000 },
			anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger_fp' },
			prop = { model = 'prop_cs_burger_01', pos = { x = 0.020000000000004, y = 0.020000000000004, y = -0.020000000000004}, rot = { x = 0.0, y = 0.0, y = 0.0} },
			usetime = 2500,
		}
	},`

with the new option "maxStackEachSlot" you can define a number, for example 32. You can't put this item more than 32 in each slot

**Comment by thelindat** [comment]
You're free to add it to your server but it's not something I'm adding here.
