### ISSUE TITLE
bt-target issues

### ISSUE THREAD

**Issue by benzon** [thelindat/linden_inventory#181]
**Describe the bug**
I know this is bt-target related, but the adviced version dos not got a issue tracker sadly, so gotta post it here and hope @OfficialNoms can read it off here.

When not with in reach of the POI, the bt-target menu glitches quite a bit, it sometimes just glitches of the screen shows the arrow and you have to hit escape to get it to remove the curser.

It picks up POI's on a way to fare range, if you target the area, i think it should not show the option unless you are with in propper range, since thats confusing.

Dumpsters dos not look to be integrated, think they should be would make the most sence if they where.

Shop Zone's need to have a different set of coords compared to normal shops, since it looks quite stupid you have to look down in to the ground to buy from a shop, the zone should be located on the counter, would make more sence to be honest.

**Comment by benzon** [comment]
Noms moved it to his bt-target repo :)

**Comment by thelindat** [comment]
We don't use this bt-target stuff and it's all separate, this stuff was submitted by Leah to help people who weren't sure how to get started.

If somebody wants to setup a config file for bt-target I'll accept it, otherwise I just want to focus on bugs or minor improvements for the time being.
