### ISSUE TITLE
Cant use weapon after 1.8.3 Update

### ISSUE THREAD

**Issue by QuickValve** [thelindat/linden_inventory#184]
**Describe the bug**
I cant use any weapon after the new update, i've updated the es_extended

**To Reproduce**
1. Update the inventory
2. Try to use any weapon

**Expected behavior**
I can use any weapon

**Screenshots**
N/A
**Additional context**
N/A

**Comment by Saitama5230** [comment]
up, i have this problem too

**Comment by thelindat** [comment]
Apparently this was caused by the last PR and should be fixed now.
