### ISSUE TITLE
Documentation about adding Weapon Component ( Flashlight, suppressor )

### ISSUE THREAD

**Issue by astron51** [thelindat/linden_inventory#185]
Hello :D 
First off, Thanks for this amazing inventory System 💯 

I would like to understand how to add Weapon Component to weapon

**Comment by astron51** [comment]
Never mind , my brain is dead for the day.
I just realize I can use metadata for this

**Comment by Nycto10K** [comment]
hey.. can you teach me how to add weapon attachments I still can't find on how to do it

**Comment by 1489259653** [comment]
so, how to add component

**Comment by 1489259653** [comment]
well how to add a addon weapon for ox_inventory
