### ISSUE TITLE
Nothing else can be used after refueling LegacyFuel Linden

### ISSUE THREAD

**Issue by lush0n3** [thelindat/linden_inventory#189]
**Describe the bug**
When refueling it works fine, but when stopping refueling, after this you cannot use any more items until you reconnect from the server.

**I uploaded a short video showing the problem.**

**Screenshots/Video**
https://youtu.be/8MwwcF1lRq4

**Comment by jrence** [comment]
yea we have same issue on this i found out this before but no one can tell me the fix ...

**Comment by thelindat** [comment]
Fixed with latest release.
