### ISSUE TITLE
Vending Shops by Hash with bt-target

### ISSUE THREAD

**Issue by AlfyM8** [thelindat/linden_inventory#190]
No so much a feature or request as more of a general question ; how would I go about using bt-target with the current shop layout to work when looking at certain hashes of vending machines. 

I've looked at client/main.lua to see how its currently set up and I'm not seeing a way to define it without breaking other things.

I suppose this would use the exports("AddTargetModel") as I used it with the previous shop/inventory I had before migrating over to yours. 

Any insight would be appreciated, if not I understand

**Comment by thelindat** [comment]
It would require some changes in the shop code, since it's setup for shop ids in specific locations. Take a look at the serverside event for openInventory to see how it sets the shop up.

Personally I wouldn't want an inventory for a vending machine.

**Comment by AlfyM8** [comment]
I took a look and it just confused me more. To be honest I can see what you mean with inventory with vending machines, but at the same time using a menu slightly bugs me also ; if I could do away with menu and E trigger events I'd be happy with myself 😂

On a unrelated side note, is there a way to make it so you can open and create police evidences from anywhere using the /evidence command? 

I've looked at those events well, and it all seems way out of my league and knowledge of lua. I'm learning new things every day though, which is progress I feel.

**Comment by Leah-UK** [comment]
You're best off asking these questions in the Discord.

**Comment by AlfyM8** [comment]
I apologize ; i honestly forgot about the discord. 

Before I close, thank you @thelindat for releasing such a great inventory system. Its honestly a game changer and it was really simple to migrate over to ESX Legacy with your version of Extended. Amazing work <3
