### ISSUE TITLE
expected ')'

### ISSUE THREAD

**Issue by dunak-debug** [thelindat/linden_inventory#192]
fix >>

https://github.com/thelindat/linden_inventory/blob/ac4bb158cf2e6c1716b6c4cf708c12e58afe6fb1/client/main.lua#L932

**Comment by thelindat** [comment]
One day I'll figure out how I manage to copy these changes from one version of the inventory to another and stuff is missing.

**Comment by dunak-debug** [comment]
dont worry we still love you
