### ISSUE TITLE
Clicking and draging some items will use the items on hotbar

### ISSUE THREAD

**Issue by Daemonns** [thelindat/linden_inventory#194]
**Describe the bug**
when equipped with gun or ussable items and then when u drag item to 1st to 2nd inv will use the item if you click something while inv is on and while moving the mouse cursor the player cam moves flickout

**To Reproduce**
1open inv while theres ussable item or gun on hotbar 1 
2. try to click some things or drag it will shoot or used the item

**Comment by thelindat** [comment]
I have no fucking idea what you just said

**Comment by ScaredDonut** [comment]
I think he is trying to say when you're in the inventory menu and a useable item is equipped (I assume he is referring to the quick access bar/menu?) and them when you drag the item to a 2nd inventory (such as ground, trunk, etc) the item will be used and then when the inventory is clicked the player camera moves with the inventory UI stuck on screen.

Then again, he could've said anything. 😂

**Comment by Daemonns** [comment]
sorry for my english 😂
