### ISSUE TITLE
Weapons lose bullets

### ISSUE THREAD

**Issue by Apolo-sys** [thelindat/linden_inventory#197]
**Describe the bug**
When you have a weapon for example (weapon_combatpistol) with full ammo and you exit and rejoin into the server you equip the gun and press R to reload, it removes the bullets from your inventory even though the gun already had ammunition in it.

**To Reproduce**
1 - Join the server.
2 - Give yourself a weapon  for example weapon_combatpistol.
3 - Give yourself ~30 ammo-9.
4 - Reload the weapon.
5 - Disconnect.
6 - Connect to the server.
7 - Check the weapon ammo in your inventory you will see that the gun is fully loaded.
8 - Close the inventory and equip the weapon in your hands.
9 - Press R and it removes the bullets from your inventory when the gun already had full ammo.

**Expected behavior**
You can't reload because the weapon its fully loaded.

**Comment by outsider31000** [comment]
if you relog it fixes, but every time you need to relog. so yeah it happens to me too
