### ISSUE TITLE
When using qtarget,  job restricted shops don't update on job change.

### ISSUE THREAD

**Issue by TheRealRSG** [thelindat/linden_inventory#198]
**Describe the bug**
If using qtarget, shop access does not update when switching jobs.

**To Reproduce**

Essentially, Log onto the server with a job such as the ambulance job, then change your job to LSPD, and go to your police armory location, and hold left alt to access shop via qtarget. You will find that it does not appear.

**Expected behavior**
I expected to be able to access the police armory via qtarget(left alt) after changing to the police job.

**Screenshots**

**Additional context**

**Comment by thelindat** [comment]
It does update, that's how ESX.PlayerData and imports work; I've tested this stuff a million times and I can assure you that they appear. Ensure you've got the correct position and update your qtarget to the latest if you're having troubles (changes to raycasting).
