### ISSUE TITLE
Few stash, item features, shop suggestions

### ISSUE THREAD

**Issue by Strinousek** [thelindat/linden_inventory#199]
**- Export / Event to push items into specific stash**
> So currently the inventory isn't really done in a way that allows us to use any kind of event or export to basically push an item into a specific stash.
> I know this isn't really a thing you need much, but because I'm creating an armory system, it really isn't good to put items into player's inventory and force him into putting the items into the stash by himself in action.
> If there would be an event / export to put items into the specific stash right on server, it would be awesome.

**- Item limitation per inventory**
> I know this is a pretty much weird suggestion considering the fact that esx legacy a.k.a 1.3 works on weight system, but it would be nice to limit player capacity of specific items. For example. limiting player's ammo capacity per inv. Players can now have basically unlimited amount of ammo until it player's inventory weight doesn't reach the maximum weight.
> I did some edits to most of my resources in order to not allow player to pass 250 m9 bullets, but player can still obtain bullets through other players. As I don't really want to change the structure too much so I can update the resource without any problems, it would be nice to have some sort of this feature configurable.

**- Shop features**
> So the current shop system works on a preconfigured basis. And there are few things that could be pretty useful.
> Add an export / event in order to create shop from other resources.
> Remove markers / make specific shops openable only by an export / event.

**Comment by thelindat** [comment]
Shop system is likely to be revamped in a big future update. Right now anything that could be considered a breaking change needs to wait.

Item limits are not happening anytime soon as a standard feature.

There's already an event for GiveStash which moves items from the inventory to a stash.
