### ISSUE TITLE
Inventory gets wiped

### ISSUE THREAD

**Issue by Trey2k** [thelindat/linden_inventory#20]
**Describe the bug**
If a player gets disconnected while they are in their inventory it gets wiped. This only appears to happen with player inventories not vehicle inventories.

**To Reproduce**
1. Open your inventory
2. press F8 and quit
3. Reconnect and your inventory is gone

**Comment by thelindat** [comment]
I've located the issue, will work on a fix and testing it when I get home.

**Comment by thelindat** [comment]
Hopefully resolved, let me know.

**Comment by Trey2k** [comment]
> Hopefully resolved, let me know.

Can confirm it is resolved, thanks linden!
