### ISSUE TITLE
Weapon Ammo Bug

### ISSUE THREAD

**Issue by ImF36e** [thelindat/linden_inventory#200]
**Describe the bug**
When you divide the ammunition into multiple slots in the inventory, the moment you reload it's like it's infinite and doesn't go to remove the ammo.

**To Reproduce**
1. Divide the ammo in multiple slots
2. Reload the weapon
3. The ammo doesn't get removed when you reload 

**Expected behavior**
The ammo get removed from the inventory when i reload, even if they are divided.

**Screenshots**
None

**Additional context**
None

**Comment by thelindat** [comment]
Release, or current commit.

**Comment by ImF36e** [comment]
current commit

**Comment by maxcamorra** [comment]
Yes I have the same bug, just tested it out.
