### ISSUE TITLE
Cant shoot after making a role

### ISSUE THREAD

**Issue by InLoveWithLua** [thelindat/linden_inventory#207]
**Describe the bug**
If you shoot and while he is reloading make a role you can no longer shoot afterwards.

**To Reproduce**
1. Shoot (In my case with pistol)
2. when you have 0 bullet left and he reload you make a role
4. you cant shoot

**Expected behavior**
On a roleplay server with many people, it is normal to roll while reloading. For this reason, the weapon should be loaded and ready to fire after rolling

**Additional context**
I don't want to open up another topic. Please linden can you watch shooting again on the motorbike or in the car? It's just very buggy, sometimes it doesn't work. Many players complain that it is a big problem. 

PS love your work. I'm grateful for people like you in the community take all the time you need bro Real life always comes first Peace

**Comment by thelindat** [comment]
>  it is normal to roll while reloading

This some matrix sort of action flick? Tell them they clearly dropped their mag ridroll for now. It’ll be resolved in 2.0 and _maybe_ I’ll push a fix if I get it done before other things are ready to go.

**Comment by thelindat** [comment]
Yeah testing default behaviour, you can't reload guns while reloading. Since the reload used by the inventory isn't default and forces the player to reload, it bugs out.

The fix is to prevent reload while performing certain actions, such as rolling.
