### ISSUE TITLE
inventory does not empty completely after death

### ISSUE THREAD

**Issue by RobiZona** [thelindat/linden_inventory#210]
Hello!! 
I have tested this error in several ways, after the death of the character, if an object is in the middle of the inventory and not in the first free slot then it is not removed, if instead the object is in the first slot it is removed and all the split of the same object
essentially the `RemoveItemAfterDeath` function of esx_ambulancejob does not work, I tried to change it with another writing

```
RegisterNetEvent('esx:onPlayerDeath')
AddEventHandler('esx:onPlayerDeath', function()
    local xPlayer = ESX.GetPlayerFromId(source)
    local money = xPlayer.getMoney()
    local items = xPlayer.getInventory()
    local player = GetPlayerPed(source)
    local coord = GetEntityCoords(player)
    if xPlayer.getMoney() > 0 then
		xPlayer.removeMoney(xPlayer.getMoney())
    end
    for i= 1, #xPlayer.inventory, 1 do
        if xPlayer.inventory[i].count > 0 then
            if xPlayer.inventory[i].name ~= 'paperbag' then
                xPlayer.setInventoryItem(xPlayer.inventory[i].name, 0)
                print(i)
            end
        end
    end
    id = id + 1
    TriggerClientEvent("--[[some scripts--]]", -1, id, items, money, coord)
end)
```
but it doesn't work like that either, the print gives me in console 
1 if the object is in slot 1,
2 if there are objects in the first and second slot,
but if I have an object in slot 10 this is not detected even after doing `/ saveinv`

i made a little video for explain the problem
https://streamable.com/9g9tvj

**Comment by RobiZona** [comment]
Maybe i found the problem.
i looked for function "setInventoryItem" and is different from es_extended legacy standard

ex_extended standard / player.lua
```
self.setInventoryItem = function(name, count)
	local item = self.getInventoryItem(name)

	if item and count >= 0 then
		count = ESX.Math.Round(count)

		if count > item.count then
			self.addInventoryItem(item.name, count - item.count)
		else
			self.removeInventoryItem(item.name, item.count - count)
		end
	end
end
```

es_extended linden / player.lua

```
self.setInventoryItem = function(name, count, metadata)
	exports['linden_inventory']:setInventoryItem(self, name, count, metadata)
end
```

so this code
```
for i= 1, #xPlayer.inventory, 1 do
       if xPlayer.inventory[i].count > 0 then
                xPlayer.setInventoryItem(xPlayer.inventory[i].name, 0)
                --print(i)          
       end
end
```
how does it get to work?

Thank You

**Comment by thelindat** [comment]
It's a slot based inventory, unlike ESX. You can't just try to clear a slot that has nothing in it.

```lua
TriggerEvent('linden_inventory:clearPlayerInventory', source)
```
