### ISSUE TITLE
Weapons not shooting after reloading inside a car

### ISSUE THREAD

**Issue by d3rp-jsx** [thelindat/linden_inventory#212]
**Describe the bug**
Weapons not shooting after reloading inside a car

**To Reproduce**
1. Shoot inside a car and wait for reload
2. Try to shoot again

**Expected behavior**
Weapons keep shooting after reloading

**Screenshots**
https://streamable.com/jcjmsy

**Comment by ProjectRogueRP** [comment]
This to happens to our players

**Comment by InLoveWithLua** [comment]
+1 not only in cars it happen in almost all vehicles its randome sometimes shot work and sometimes doesnt
