### ISSUE TITLE
syncInventory

### ISSUE THREAD

**Issue by FrankHUN88453** [thelindat/linden_inventory#218]
I follow all steps !
![image](https://user-images.githubusercontent.com/77191091/129970125-5e81f783-e969-4313-9603-28aa78505126.png)

**Comment by ItzSwindle** [comment]
Same

**Comment by Duskimm** [comment]
@FrankHUN88453  this is because you aren't using the lindem es_extended to lindem_inventory.
https://github.com/thelindat/esx-legacy ( DOCUMENTATION ).

https://github.com/thelindat/es_extended   ( ES_EXTENDED )

**Comment by ItzSwindle** [comment]
i am using linden es_extended

**Comment by FrankHUN88453** [comment]
Thanks
