### ISSUE TITLE
Give Button

### ISSUE THREAD

**Issue by EGUltraTM** [thelindat/linden_inventory#22]
I would love to see a give button in this inventory. 

it is really an awesome thing. You should add an donate button or something. 
would donate something. 

Thanks for taking over this project and doing such nice things with it <3

Also during the frequent updates which is nice it would be awesome to use a translation system with an file :)

**Comment by Trey2k** [comment]
Hey there is a give button btw :)

**Comment by thelindat** [comment]
Already have a give button, thanks to Trey.
