### ISSUE TITLE
Items disappearing after dropping

### ISSUE THREAD

**Issue by maxcamorra** [thelindat/linden_inventory#24]
**Describe the bug**
If I drop things and then open inventory with f2 again the item is disappeared that i dropped, so i cant pick it up anymore

**To Reproduce**
1. Drop Item
2. close inventory
3. open inventory again
4. no item in the drop window

**Expected behavior**
it should show the items that were dropped at this place

**Comment by thelindat** [comment]
Is that with https://github.com/thelindat/linden_inventory/commit/25eea592aad03f65a5f5cd40cb6be8782e1eab58?

**Comment by maxcamorra** [comment]
Yes

**Comment by thelindat** [comment]
I can't reproduce this issue

**Comment by maxcamorra** [comment]
ok i tried your new commits now 
maybe it works now

**Comment by maxcamorra** [comment]
No it's still not working, the dropped items doesnt show up for me in the inventory...

**Comment by maxcamorra** [comment]
Ok i fucked up somewhere :( i tried the latest release and now its working
