### ISSUE TITLE
Item stack splitting

### ISSUE THREAD

**Issue by PhotoshopLOL** [thelindat/linden_inventory#26]
**Is your feature request related to a problem? Please describe.**

> If I want to quickly split half of my item stack to give to a friend, I have to manually input half of the item's count into the count box.

**Describe the solution you'd like**

> Rust has a great solution to this since you can split your items by holding MMB on an item and dragging & dropping it to a vacant slot. This splits the item into halves seamlessly without additional user input. Also works with odd numbers (leaves 1 in the origin item stack).

**Describe alternatives you've considered**

> Enable drag & drop with MMB that takes half of the item's count and adds it to the dropped slot (either left or right inv)

**Additional context**
![rust-stack-split](https://user-images.githubusercontent.com/7889116/115473434-50c32280-a26e-11eb-96cc-12e6ca0de143.gif)

I know this is just for ease-of-life but would be nice to have it 💯

**Comment by thelindat** [comment]
Done for next release.
