### ISSUE TITLE
Stack glitch with shops

### ISSUE THREAD

**Issue by DoluTattoo** [thelindat/linden_inventory#284]
**Describe the bug**
You can stack non-stackable items when buying them from shops

**To Reproduce**
1. Add `parachute `and `phone` to `data/shops.lua`,
2. Buy some parachutes by drag&drop on the same slot of your inventory,
3 Buy some phones using the same way.

**Expected behavior**
It should just use a free slot instead or send an error notification

**Screenshots**
Doesn't need a screenshot ^^

**Additional context**

**Comment by dolutattoo** [comment]
Sorry, the problem is not fixed :s
