### ISSUE TITLE
Use empty png as image for no-image-declared items

### ISSUE THREAD

**Issue by drkm43** [thelindat/linden_inventory#29]
**Is your feature request related to a problem? Please describe.**
No, this is not a problem maybe a feature to add if linden is okay with it

**Describe the solution you'd like**
Maybe a file like "empty.png" or "noimage.png" can be used instead of the broken image icon that shows on current update with this type of items

**Describe alternatives you've considered**
I cant see any other solution

**Additional context**
![image](https://user-images.githubusercontent.com/49250139/115855864-0be4ea80-a42c-11eb-932c-48a2d3841362.png)

**Comment by thelindat** [comment]
Doesn't need a transparent image. https://github.com/thelindat/linden_inventory/commit/9ee85fab451b287b76912782ddf6049ec9ecce7f
