### ISSUE TITLE
Allow Selling to shops

### ISSUE THREAD

**Issue by Trey2k** [thelindat/linden_inventory#30]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way to let players sell to shops as well as buy from them.  

**Describe alternatives you've considered**
Another shop type for selling would work as well

**Comment by Ruqen** [comment]
This would make no sense in RP.

**Comment by Trey2k** [comment]
> This would make no sense in RP.

I disagree, I am not saying every shop. But it would be nice to be able to use the same UI for selling items as well as buying items. This way in RP we can have suppliers to merchants.

**Comment by benzon** [comment]
Think what you are trying to say here.

ex. when having some sort of rare item, could be gold so on, you can sell it to a npc via the ui, insted of having to some sort of other trick.

It makes sence with out doubt.

**Comment by kFxDaKing** [comment]
> This would make no sense in RP.

Not every server is RP.

**Comment by Senlar** [comment]
Would be great for player funded trade locations like a pawn shop. I would love this!
