### ISSUE TITLE
Owned vehicle storage not being saved in data abse

### ISSUE THREAD

**Issue by Trey2k** [thelindat/linden_inventory#34]
**Describe the bug**
When items are stored in a owned vehicle they do not get stored in the database. 

**To Reproduce**
1. Store an item in a owned vehicle
2. Restart linden inventory
3. No entry in the database has been created and thus the item is gone

**Expected behavior**
It to be stored in database

**Additional context**
The core of the issue seems to be ```local result = exports.ghmattimysql:scalarSync('SELECT owner FROM owned_vehicles WHERE plate = @plate', {
					['@plate'] = plate
				})``` returning nil on line 204 of server/functions.lua

**Comment by thelindat** [comment]
What's the plate format? Might be querying the incorrect plate

**Comment by Trey2k** [comment]
> What's the plate format? Might be querying the incorrect plate

While testing I was using the plate 'NJR 116', I printed it out to confirm that was the plate the script was using too. I also ran it manually and it did return a row.
![image](https://user-images.githubusercontent.com/7241029/116323275-81c1bc80-a772-11eb-8d51-ffb284f2139d.png)

**Comment by thelindat** [comment]
The plate being queried by the inventory may be 'NJR 116 ' since plates are supposed to be 8 characters long, can you confirm if that is the case?

**Comment by Trey2k** [comment]
> The plate being queried by the inventory may be 'NJR 116 ' since plates are supposed to be 8 characters long, can you confirm if that is the case?

'MZU 931 ' can confirm, but its odd. I have just left it on the default settings for plate format

**Comment by Trey2k** [comment]
Ive fixed by changing Config.PlateNumbers  = 4 instead of 3. But you may consider adding support for the default settings

**Comment by LlamaPalooza89** [comment]
I know this is closed, but do plates have to be a certain length for the vehicle inventory to be saved? or will Config.TrimPlate= true fix that issue?
