### ISSUE TITLE
Hotbar no longer working after using weapon addon

### ISSUE THREAD

**Issue by Okkie-NL** [thelindat/linden_inventory#35]
**Describe the bug**
When you put a weapon addon like the Pistol Suppressor on your hotbar and activate it while no gun is out, the Action Bar no longer works.

**To Reproduce**
1. Put a pistol suppressor on the hotbar and activate it by pressing the correct hotkey (make sure not to have your weapon in hand).
2. Now try to activate anything else on the hotbar.

**Expected behaviour**
Message that you need the correct weapon in your hand and not bug out the hotbar.

**Additional context**

**Comment by thelindat** [comment]
Using latest commit, not release?

**Comment by Okkie-NL** [comment]
I have the latest release. Is this issue solved after that? If yes, I will try to reproduce it on the latest commit.

**Comment by Okkie-NL** [comment]
Hi. Tried to reproduce it on the latest commit and it seems to work correctly now. Thank you.
