### ISSUE TITLE
When transferring items from the car to your inventory it bugs out

### ISSUE THREAD

**Issue by Okkie-NL** [thelindat/linden_inventory#36]
**Describe the bug**
When moving items from a car inventory and setting 1 as the number of items to move over it can cause the inventory to no longer allow you to stack the items.

**To Reproduce**
1. Put the amount of items to transfer on 1.
2. Move items over from your inventory to the car.
3. Move the items back and the inventory no longer allows you to stack them and gives an error in the console.

**Expected behavior**
Stack items without any issues.

**Screenshots**
Errors:
![image](https://user-images.githubusercontent.com/10367379/116329510-c7f73a00-a7cb-11eb-9d29-72f01d3b772f.png)

Inventory:
![image](https://user-images.githubusercontent.com/10367379/116329539-db0a0a00-a7cb-11eb-99ca-3b8c8a8d1f0e.png)

**Comment by thelindat** [comment]
I believe https://github.com/thelindat/linden_inventory/commit/8943d8d634df10d5919608fd30b6aeca2d04bdab will resolve it (though finding the cause of metadata being undefined would be nice :\)

**Comment by Ruqen** [comment]
Couldn't reproduce, like lindat said

https://github.com/thelindat/linden_inventory/commit/8943d8d634df10d5919608fd30b6aeca2d04bdab

This commit resolved it.

**Comment by Okkie-NL** [comment]
Thank you for solving!
