### ISSUE TITLE
Logs write wrong messages in evidence

### ISSUE THREAD

**Issue by maxcamorra** [thelindat/linden_inventory#39]
**Describe the bug**
It's showing wrong messages in logs when i use the evidence.

**To Reproduce**
1. Go to evidence-spot
2. Type /evidence 1
3. Put item inside
4. you see that it writes taken from evidence although i put it inside the evidence

**Expected behavior**
It should show that i have put an item inside and not taken from evidence

**Comment by thelindat** [comment]
This was fixed days ago.
