### ISSUE TITLE
Players still have components after death

### ISSUE THREAD

**Issue by Gigavat02** [thelindat/linden_inventory#41]
**Describe the bug**
When a player has bought a weapon and has attached components on it, after he dies with a weapon on his hands and his inventory gets cleared with this event: TriggerEvent('linden_inventory:clearPlayerInventory', xPlayer), when the player goes and buys the same weapon it still has the attachments on it, although the inventory says that it has no components on him.

**To Reproduce**
1. Buy a weapon
2. Attach a component on it
3. Kill your character with the weapon on his hands
5. Respawn
4. Buy the same weapon

**Expected behavior**
The player shouldn't have the components on his weapon after his inventory got cleared with the event 'linden_inventory:clearPlayerInventory'

**Screenshots**
https://i.imgur.com/Nk6JUbF.png

**Additional context**
The problem might be that because when the player dies with his weapon on his hand and the weapon falls on the ground, the metadata of it doesn't get cleared.

**Comment by thelindat** [comment]
Should be resolved.
