### ISSUE TITLE
Weapons/items get removed randomly

### ISSUE THREAD

**Issue by maxcamorra** [thelindat/linden_inventory#42]
**Describe the bug**
put weapon inside and then got removed from trunk

**To Reproduce**
1. open trunk
2. put weapon inside (here for example appistol)
3. close trunk and let someone else watch inside
4. weapon got removed

**Expected behavior**
it should stay inside

**Screenshots**
https://files.fm/f/jveqarjex  <-- Video to show what have been done

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/116943015-161da900-acb6-11eb-9b37-52b2b9d72c85.png)
And here we see the terrible video host in it's natural habitat. Spending 20 minutes buffering a 5 minute video just for the entire thing to freeze up and need to refresh and rebuffer is a good time.

Issue has not been reproduced in a live server environment.

**Comment by maxcamorra** [comment]
Yeah sorry I got it from a player who have this bug and some others had the same bug aswell. 20 minutes ago someone got a Knuckle and have put it inside the car, closed inventory later looked again inside and it was away.

**Comment by thelindat** [comment]
Unless you can provide script errors or warnings (nil values, item failed validation, etc) I can't help.
I haven't encountered the issue, and nobody has reported it on an active server.

**Comment by maxcamorra** [comment]
Hmm ok

**Comment by maxcamorra** [comment]
I got a new message of a player from me. He told me he already cleared cache and sometimes it happens that the inventory shows as empty although its not empty in the database and also it shows above the inventory 0 instead of the weight and the drop window is not there, after he restarts the game the inventory shows correctly again but after a while maybe starts again to show as empty.

**Comment by maxcamorra** [comment]
it happens when people are farming drugs and the hotbar is not empty so the drugs get automaticall into the hotbar and then it happens that the inventory doesnt work and show nothing.

**Comment by Arliind** [comment]
@maxcamorra take a look at the newest version. It has a sql fix which should hopefully fix your problem

**Comment by maxcamorra** [comment]
@Arliind you know which commit is this?

**Comment by Arliind** [comment]
Should be the one where he edits the .sql file. I'd recommend updating to the latest commit though
