### ISSUE TITLE
Using items with no use. Bugs inventory

### ISSUE THREAD

**Issue by ElusionPDX** [thelindat/linden_inventory#43]
**Describe the bug**
If you use a item that doesn't have a uses setup for it, it will bug out the system and you can no longer use any item in your inventory. 

**To Reproduce**

Add any item to your server that has no use and its just a item for other scripts to check a item amount 
try to use it and it will bug out the system. no other item can be used once this happens and you can A relog or B restart the inventory

**Expected behavior**
for nothing to happen and not bug out

**Comment by thelindat** [comment]
Items are registered as usable if using `ESX.RegisterUsableItem` or added to `shared/items.lua` - anything you don't want usable shouldn't be added.

**Comment by ElusionPDX** [comment]
They are not added. they are just items in the DB for item checks like c4 doing a bank job. But if you happen to try and use the item then you cant use any other item after.

**Comment by thelindat** [comment]
If an item is not registered with ESX or in Config.ItemList then it is not usable. If it is not usable, nothing will trigger.
I am spamming the hotkey for an item as well as trying to use it from the inventory and it does not do anything.

**Comment by ElusionPDX** [comment]
Well for me and any one else on the server when i try to use a item not in one of the 2 systems (registered with ESX or in Config.ItemList) i cant use any item after

**Comment by ElusionPDX** [comment]
Sorry for the flickers for some reason NVidia wants to try and rec both screens..
https://streamable.com/hwhe86

**Comment by thelindat** [comment]
Okay, now try using the explosives first before trying to use the metal detector.

**Comment by ElusionPDX** [comment]
did you push a update that i need to apply first.?

**Comment by ElusionPDX** [comment]
Does the same.  Once you try to use and none added item you cant use any added item.

https://streamable.com/q1ewuu

**Comment by thelindat** [comment]
Items that are not registered _do not cause this issue_.
Unregistered items would previosly send to the server and then say "hey, not usable so tell the client not to do anything with it". At this point, they don't even send anything to the server.

**Comment by ElusionPDX** [comment]
Im confused did you pushed a patch for it to git and i cant see it in the commits or it hasn't been pushed yet.

**Comment by ElusionPDX** [comment]
I take back my question as i looked thru the past update logs and seems you already fixed this issue i was still running 1.2.5. now on 1.2.8 and the issue is solved.
