### ISSUE TITLE
weapons cant get reloaded

### ISSUE THREAD

**Issue by maxcamorra** [thelindat/linden_inventory#48]
**Describe the bug**
some weapons cant get reloaded, for example appistol

**To Reproduce**
1. take weapon in hand
2. use ammo-9 or use "R"
3. you cant load the ap-pistol with 9mm ammo

**Expected behavior**
all weapons should be able to reload

**Comment by maxcamorra** [comment]
when i reconnect i can reload the weapons one time and then never again it always says cant load the weapon with 9mm ammo, also tried with smg, the same problem

**Comment by maxcamorra** [comment]
every weapon doesnt work anymore to reload haha :D

**Comment by thelindat** [comment]
It's fixed.
