### ISSUE TITLE
weapons get removed when 0 ammo in it

### ISSUE THREAD

**Issue by maxcamorra** [thelindat/linden_inventory#49]
**Describe the bug**
weapon get "unlimited" ammo because it get removed when 0 ammo in it

**To Reproduce**
1. take weapon in hotbar
2. use the key for taking the weapon from hotbar
3. shoot out all ammo
4. weapon gets removed, now pick it again with the key
5. See error, the amount of ammo like it was before you taking it out --> "unlimited" ammo

**Expected behavior**
should save all ammo and dont remove the weapon

**Comment by thelindat** [comment]
Weapons do not get holstered when out of ammo?

**Comment by maxcamorra** [comment]
![image](https://user-images.githubusercontent.com/78707245/117324952-939d1100-ae90-11eb-94e7-7d0f8e1c8da2.png)
This happens after ammo is 0 and i holster the weapon, also the animation still is there although its already holstered and in addition to that i get the notify, that I cant open the inventory

**Comment by maxcamorra** [comment]
ok seems to work now
