### ISSUE TITLE
Items in drop disappear

### ISSUE THREAD

**Issue by maxcamorra** [thelindat/linden_inventory#53]
**Describe the bug**
Items in drop disappear

**To Reproduce**
1. Put item in drop
2. close inventory
3. no marker got placed
4. items disappeared

**Expected behavior**
marker should show up and items should be there still

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/117540707-c5aaa080-b053-11eb-84a6-802449faa734.png)


Got the new files and config?

**Comment by maxcamorra** [comment]
Yes I downloaded the latest release.

**Comment by maxcamorra** [comment]
![image](https://user-images.githubusercontent.com/78707245/117544671-caa32c00-b022-11eb-9864-6da2fcb073b8.png)
this what should be inside

after closing inventory: 
![image](https://user-images.githubusercontent.com/78707245/117544693-d989de80-b022-11eb-814a-2f600ae0f756.png)

openeing inventory again, nothing is in there in the drop:
![image](https://user-images.githubusercontent.com/78707245/117544703-e4447380-b022-11eb-909d-356594713e98.png)



Also as you can see drop doesnt have a number/index now like it had in version before 1.3

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/117550067-77ac9180-b081-11eb-917c-ad2b9d249be3.png)

Your drop just straight up isn't being created; look at the server console because there ought to be an error.

**Comment by maxcamorra** [comment]
there is no error

**Comment by maxcamorra** [comment]
Ok i found the problem. It was because I had logs on true but i didnt have the necessary script for writing logs :D
