### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by jumpjet91** [thelindat/linden_inventory#55]
I see an error in console during update Item weight inventory, it pass a string not a number. It's easy to fix

file SERVER-->player.lua --> replace all **xItem.weight** to **tonumber(xItem.weight)**

[player.zip](https://github.com/thelindat/linden_inventory/files/6446164/player.zip)

**Comment by jumpjet91** [comment]
Missing 2 function clientside on version 1.3.0
`error = function(msg)
	TriggerEvent('mythic_notify:client:SendAlert', {type = 'error', text = msg, length = 2500})
end

inform = function(msg)
	TriggerEvent('mythic_notify:client:SendAlert', {type = 'inform', text = msg, length = 2500})
end`

**Comment by thelindat** [comment]
Those functions were specifically removed. I'm certainly interested in why your items are passing weight as a string, because converting to a number shouldn't be necessary (and hasn't been a concern on an active server).

**Comment by jumpjet91** [comment]
i don't know why but for v1.3.0 i did this fix for work
