### ISSUE TITLE
Inventory Getting Stuck

### ISSUE THREAD

**Issue by Arliind** [thelindat/linden_inventory#57]
**Describe the bug**
https://i.vgy.me/aumGib.png

When closing the inventory sometimes, this happens. No idea why. This started happening after updating to 1.3.0

It doesnt happen all the time but I was testing things out with items and dropping them and then it just got stuck. I tried using the command to close my inventory but it kept posting this error

**Comment by thelindat** [comment]
https://github.com/thelindat/linden_inventory/commit/fa6113e04cf26eac54eabd3b15260d83577ee0e8
Should fix it
