### ISSUE TITLE
Issue with removing items that contain meta data

### ISSUE THREAD

**Issue by Trey2k** [thelindat/linden_inventory#6]
**Describe the bug**
Items with meta data cannot be removed from the inventory via the command or xPlayer.removeInventoryItem(). Passing no meta data to xPlayer.removeInventoryItem() also will not remove it.

**To Reproduce**
2. give it to yourself a water with metadata with /giveitem 1 water 1 pee
3. try to remove it with /removeitem 1 water 1 pee
4. try to remove it with /removeitem 1 water 1

**Expected behavior**
The stone to be removed

**Screenshots**
![image](https://user-images.githubusercontent.com/7241029/114769850-94bea080-9d1f-11eb-9d08-59e7edd0869a.png)
![image](https://user-images.githubusercontent.com/7241029/114769888-a2742600-9d1f-11eb-8097-44ca38e2de5f.png)
![image](https://user-images.githubusercontent.com/7241029/114769947-b9b31380-9d1f-11eb-9619-c1720f16ff39.png)

**Comment by thelindat** [comment]
Resolved; let me know if there is any other issues with metadata

**Comment by Trey2k** [comment]
Seems to be all fixed, except if you do not pass any meta data it wont just remove it. Not as big of a deal but is this expected behavior?
