### ISSUE TITLE
Job Grade Checking for Shops

### ISSUE THREAD

**Issue by Leah-UK** [thelindat/linden_inventory#61]
Title. The script already checks for jobs themselves, it would be nice if they also checked for grade. Possibly in an array format to allow for multiple grades to access.

I am willing to do this and merge - when I have time.

**Comment by thelindat** [comment]
Grade for accessing a shop? You can already restrict purchase of weapons to a grade, if that's what you mean.

**Comment by Leah-UK** [comment]
I meant so players can't even open the shop if they aren't of a specific grade in their job. But the restricting of items to a specific grade is a good alternative.
