### ISSUE TITLE
Inventory with esx_policejob searching and put to the stocks

### ISSUE THREAD

**Issue by DexikCZ123** [thelindat/linden_inventory#65]
Not working search people inventory a don work give item to the stocks

**Comment by Ruqen** [comment]
What do you mean? I can't understand you

**Comment by thelindat** [comment]
You're going to have a bad time trying to use default inventory menus with this.

Go to documentation for replacing the default police body search.  
Disable the base police inventory stuff and use the stashes. There are personal lockers for players, and /evidence # while near the evidence room (set the positions in `shared/stashes.lua`)
