### ISSUE TITLE
Throw items from vehicle (able to pick up items on the ground from with in vehicle)

### ISSUE THREAD

**Issue by benzon** [thelindat/linden_inventory#66]
**Describe the bug**
When you sit in a vehicle and throw an item that works fine.

But you can pick up the item when sitting in a car, seems abit out of place

**Comment by Ruqen** [comment]
So... Throwing items in a car shouldn't be possible?

**Comment by benzon** [comment]
It should be possible thats fine, but picking them up again from with in the vehicle thats where the issue comes in.

**Comment by thelindat** [comment]
I'll disable the ability to open drops while in a vehicle later.

**Comment by thelindat** [comment]
https://github.com/thelindat/linden_inventory/commit/94ea7b22042361ec505e9b8fd3c1edf730617db3
