### ISSUE TITLE
Weapon Tints (Skins)

### ISSUE THREAD

**Issue by benzon** [thelindat/linden_inventory#69]
Add weapon tints/skins, should be straight forward to do, it's very mutch like adding components.

**Comment by Arliind** [comment]
they're already in but not as items. you add it to the metadata of the weapon

**Comment by thelindat** [comment]
I don't like handling fiddly things like this, which is why weapon components still haven't been slimmed down.
If somebody wants to do this stuff and PR it then great, otherwise I'll probably never do it even though it is a wanted feature.

I miss my 🐵

**Comment by thelindat** [comment]
Most skins are available.
