### ISSUE TITLE
Identification Cards

### ISSUE THREAD

**Issue by Utinax** [thelindat/linden_inventory#7]
**Is your feature request related to a problem? Please describe.**
No. It is just a suggestion.

**Describe the solution you'd like**
1.I think it would be better if you could change the "Sex: m" in id cards with "Sex: Male" or "Sex: Female".
2.You can add "Identity No" for every person in id cards.
3.And it would be better if you remove the steam hex from id the cards or could add a config for it like "Config.SteamHexInID = false".

**Comment by thelindat** [comment]
> 1.I think it would be better if you could change the "Sex: m" in id cards with "Sex: Male" or "Sex: Female".
Will be done.

> 2.You can add "Identity No" for every person in id cards.
> 3.And it would be better if you remove the steam hex from id the cards or could add a config for it like "Config.SteamHexInID = false".
If you use kashacters it's fairly easy to have it assign unique ids unrelated to the identifier you use. I'll change it up a bit though.
