### ISSUE TITLE
Inventory bug getSharedObject()

### ISSUE THREAD

**Issue by Tyrus2K** [thelindat/linden_inventory#75]
When I start the server I get this error saying the es_extended doesn't have that export and I even tried using your es_extended still had the same error.

![Screenshot_6](https://user-images.githubusercontent.com/84287338/118407986-5cdaae00-b67b-11eb-8aff-3c88f70cf19a.png)

**Comment by thelindat** [comment]
Check the folder name of es_extended, don't have it as anything else.

**Comment by Tyrus2K** [comment]
> Check the folder name of es_extended, don't have it as anything else.

Nope it has the same name

**Comment by Swarnadip-18** [comment]
use esx v1 final ...or else check if you have exported getSharedObject() in ur es_extended fxmanifest.lua
