### ISSUE TITLE
Translation In remove

### ISSUE THREAD

**Issue by Daemonns** [thelindat/linden_inventory#77]
**Describe the bug**
When u use an item the removed text become [en] translation removed]

**Screenshots**
![1](https://user-images.githubusercontent.com/81875858/118871257-fc1cd100-b919-11eb-9527-b40c05f169ec.PNG)

**Comment by thelindat** [comment]
https://github.com/thelindat/linden_inventory/commit/cd8cb313817f1e02e412b0cbb8313f02f6a5354a
