### ISSUE TITLE
Motel Inventory Help

### ISSUE THREAD

**Issue by LlamaPalooza89** [thelindat/linden_inventory#79]
**Is your feature request related to a problem? Please describe.**

1. **I'm using a motels script that is made for esx_inventoryhud. It includes a property.lua to add into that resource so players can use motel inventories and it opens up in the same UI as inventoryhud. Problem is, there are a few triggers/functions in it that aren't for linden-inventory.**

**Describe the solution you'd like**

2. **The property.lua file can be edited to call for the right functions and what not, I myself am stumped. I was wondering if someone could help me with this.**

**Describe alternatives you've considered**

3. **Finding another motel script that works with linden_inventory.**

**Additional context**

**Comment by thelindat** [comment]
Unlike inventoryhud you don't need extra files and a bunch of edits to set up a new stash, all you need to do is use the provided export and ensure the correct data is being sent through.

loaf_housing example
```lua
OpenStorage = function(houseid, k, v)
    exports['linden_inventory']:OpenStash({ name = ('house %s'):format(houseid), slots = 101})
end
```

Depending on how the storage works (if you stand inside a marker) you can also follow the example for esx_property
```lua
	AddEventHandler('linden_inventory:getProperty', function(cb)
		if CurrentAction == 'room_menu' then
			cb({name = CurrentActionData.property.name, label = CurrentActionData.property.label, owner = CurrentActionData.owner, slots = 70})
		end
	end)
```

The example for property is actually newer and better, and includes sending the property owner's identifier so it can get deleted by multicharacter resources.

**Comment by LlamaPalooza89** [comment]
I figured out which export to use and where to put it, but I get an error because of the identifier.

 exports['linden_inventory']:OpenStash({ name = 'Bank Deposit Box', slots = 20, owner = ESX.GetPlayerData().identifier()})
 
 This export is being put in a client.lua if that matters. I was able to get the other exports to work but obviously, I need it to be the first export I listed since it's for motels.

**Comment by thelindat** [comment]
You shouldn't be trying to do a callback, just triggering the stash directly. You need to get the motel's name and its owner - without having access to the resource (especially if it's paid) I can't help you and you'll need to work it out based on given examples.

**Comment by LlamaPalooza89** [comment]
The callback is what the developer has for opening the default inventory.....

As for the help, the error I am getting is for the identifier that is being called for in the export for your inventory. So I believe you can help without needing the source code for the motels script I am using as it has nothing to do with what your export calls for....
