### ISSUE TITLE
Glovebox freeze

### ISSUE THREAD

**Issue by maxcamorra** [thelindat/linden_inventory#8]
If I'm sitting in the car and open the glovebox and after closing i get stuck inside the car and can't leave it anymore.

**Comment by thelindat** [comment]
Are you using a seatbelt resource that activates when pressing 'K' (the default key)?

**Comment by maxcamorra** [comment]
Ah yes I do.

**Comment by maxcamorra** [comment]
Ah ok I just have to change the key :D
