### ISSUE TITLE
Mouse stuck

### ISSUE THREAD

**Issue by X00LA** [thelindat/linden_inventory#81]
**Describe the bug**
HI, Iinstalled linden_inventory as described in the install guide. After that I wanted to test it and joined my server. When I open the Inventory I can't move the mouse. It gets stuck in the middle of the screen. I doesn't have any errors in the logs or in the console.

**To Reproduce**
1. Installed linden_inventory as described.
2. Started and joined server.
3. Open inventory.

**Comment by thelindat** [comment]
You may be having a conflict with something else disabling NUI focus.

**Comment by X00LA** [comment]
I can't think of anything. I only have installed basic FiveM and all dependencies for the ESX files to get linden_inventory working. No additional mods are present. Only mod I installed separately is krz_personalmenu and jsfour-idcards. For a better description here's the list from my server.cfg:

`## FiveM default resources.
ensure example-loadscreen
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure hardcap

## ESX default resources.
ensure mysql-async
ensure async
ensure ghmattimysql
ensure es_extended
ensure esx_addonaccount
ensure esx_addoninventory
ensure esx_datastore
ensure esx_billing
ensure esx_society
ensure skinchanger
ensure esx_skin
ensure esx_accessories
ensure esx_identity
ensure esx_license
ensure esx_menu_default
ensure esx_menu_dialog
ensure esx_menu_list
ensure esx_dmvschool
ensure esx_service
ensure esx_status

## ESX secondary resources.
ensure cron
ensure jsfour-idcard
ensure LegacyFuel

## ESX Jobs
ensure esx_policejob

## ESX Shops
ensure esx_licenseshop
ensure esx_advancedvehicleshop

## Inventory
ensure linden_inventory

## Administration
ensure krz_personalmenu

## Map
ensure Verpi_Driving_School`

Could it be because of my starting order?

**Comment by Ruqen** [comment]
Can't reproduce.

**Comment by X00LA** [comment]
> Can't reproduce.

I checked if the issue disappears when I activate/deactivate different resources, but the issue still exists. I had the same problem with esx_identity, but there I could resolve the problem with a simple CitizenWait(2000) in the opening function.
Unfortunatly this doesn't work here. I will try to install everything again and hope this time it will work.

**Comment by thelindat** [comment]
There is something forcing your NUI focus to get removed when it gets initially set, based on what you're saying.

**Comment by X00LA** [comment]
Yeah, but I can't figure out what. So I start from the beginning and look over it to find what's causing it. I also have black windows all over the screen from esx_property. there must be something weird with the modules I use. I will test every module sepeartely after install. Hopefully I can find the devil which causes this.

**Comment by Ukrazna** [comment]
Yes that issue right my friend had same issue on my server and the funny part was like i didnt had that issue other friends were okay too i think it just happens maybe to random people and also cant reproduce it too

**Comment by redacid95** [comment]
Mouse input issues is FiveM game settings. Go to your GTA game settings. Change the mouse input to raw instead of Windows

**Comment by thelindat** [comment]
> 
> 
> Mouse input issues is FiveM game settings. Go to your GTA game settings. Change the mouse input to raw instead of Windows

**Comment by CaptainCorap** [comment]
did you solve the problem?
have the same problem

**Comment by redacid95** [comment]
> did you solve the problem?
> have the same problem

You should probably read, before asking.
