### ISSUE TITLE
Reloading while falling if Config.AutoReload is true

### ISSUE THREAD

**Issue by drkm43** [thelindat/linden_inventory#82]
**Describe the bug**
Client can reload weapons while falling on sky if "Config.AutoReload" is activated

**To Reproduce**
1. set Config.AutoReload bool to true, grab a weapon, ammo and fall from the highest point on the map
2. start firing until you get 0 bullets, then you will reload the weapon because the bool activated in step 1
3. doesnt has sense reloading the weapon while falling, can be fixed checking if the player is falling before reloading
![image](https://user-images.githubusercontent.com/49250139/119240044-96188f80-bb4d-11eb-990c-e25e41356f09.png)

**Comment by thelindat** [comment]
Added checks for falling and ragdolling
