### ISSUE TITLE
Drops not working

### ISSUE THREAD

**Issue by maxcamorra** [thelindat/linden_inventory#83]
**Describe the bug**
If I drop something it instantly gets removed.

**To Reproduce**
1. Open Inventory
2. drop something
3. item disappears but marker is there
4. See error in console: SCRIPT ERROR: @linden_inventory/server/main.lua:295: invalid vector field: drop

**Comment by maxcamorra** [comment]
In Addition to that after I tried to open the drop marker I can't open the inventory anymore.

**Comment by thelindat** [comment]
Should be fixed from last commit.
