### ISSUE TITLE
Bt-Target on stash or Store

### ISSUE THREAD

**Issue by Daemonns** [thelindat/linden_inventory#84]
Maybe someone Done that but i dunno how 
On store or stash 
![ee7ea9a4e69da6d13636f4361114775504cf0d26_2_690x386](https://user-images.githubusercontent.com/81875858/119261093-5a8ecb80-bc08-11eb-9261-a7c749e5814e.jpeg)

**Comment by thelindat** [comment]
I'm not putting it in baseline.

**Comment by Daemonns** [comment]
but the exports['linden_inventory']:OpenStash(police stash something) dont know how to trigger this
