### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by thelindat** [thelindat/linden_inventory#85]
Please post any recommendations for updating the documentation here (snippets, usage, FAQs, whatever).

**Comment by ScaredDonut** [comment]
Guess I have a question for the FAQ not sure if it'd qualify as a frequent question.

Is there any specific reason why you chose to go with ESX Legacy and not say ESX 1-FInal for example? I've tried moving all my stuff over to Legacy but had a few issues unfortunately. 

Thanks for this awesome inventory system by the way! ❤️

**Comment by thelindat** [comment]
There shouldn't be any compatibility issues for for v1 Final resources when using Legacy, it hasn't changed the functions. Feel free to let me know what issues you're having and I'll look into it.

> 
> 
> Guess I have a question for the FAQ not sure if it'd qualify as a frequent question.
> 
> Is there any specific reason why you chose to go with ESX Legacy and not say ESX 1-FInal for example? I've tried moving all my stuff over to Legacy but had a few issues unfortunately.
> 
> Thanks for this awesome inventory system by the way! ❤️

There shouldn't be any compatibility issues for for v1 Final resources when using Legacy, it hasn't changed the functions. Feel free to let me know what issues you're having and I'll look into it.


I went with Legacy because I want to use it personally for some of the improvements.

**Comment by ScaredDonut** [comment]
> There shouldn't be any compatibility issues for for v1 Final resources when using Legacy, it hasn't changed the functions. Feel free to let me know what issues you're having and I'll look into it.
> 
> > Guess I have a question for the FAQ not sure if it'd qualify as a frequent question.
> > Is there any specific reason why you chose to go with ESX Legacy and not say ESX 1-FInal for example? I've tried moving all my stuff over to Legacy but had a few issues unfortunately.
> > Thanks for this awesome inventory system by the way! ❤️
> 
> There shouldn't be any compatibility issues for for v1 Final resources when using Legacy, it hasn't changed the functions. Feel free to let me know what issues you're having and I'll look into it.
> 
> I went with Legacy because I want to use it personally for some of the improvements.

Thank you for getting back to me so quickly. The only major issue that I encountered is that its stopping me from spawning I assume its because I am using a different multi char script that requires some changes to the framework its self.  So not really able to test much beyond that.


You end up spawning but none of the objects have collision you just fall through the map. I can send you the README so you can see what changes need to be made if you'd like?

**Comment by thelindat** [comment]
Going to assume mf-multichar based on the falling through the map - happens a lot because of its spawning method. I can confirm that it still works with Legacy and the changes aren't that different; I can get a reference for it later

**Comment by ScaredDonut** [comment]
Yes it is! Thank you so much for your help! I'll be sure to look out for them. You're awesome :)

**Comment by thelindat** [comment]
> 
> 
> Yes it is! Thank you so much for your help! I'll be sure to look out for them. You're awesome :)

Unfortunately don't have the files anymore. All you should need to do is disable the spawning stuff in es_extended though; the other edits pretty much go through the same as before.

Going to clean up these comments later too since it's very much off-topic.
