### ISSUE TITLE
Dropping objects

### ISSUE THREAD

**Issue by Knugfan** [thelindat/linden_inventory#86]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like the idea that when you drop something, it will spawn a prop (maybe configurable by item in config) on the ground. So if I drop an item with the name phone I could in the config choose wich prop that should be when dropped. 

**Describe alternatives you've considered**
If no prop is declared by the config, you would get the standard marker that the drop function uses now.

**Additional context**
This would be cool ;) :P

**Comment by thelindat** [comment]
This is not going to be a feature. ESX itself does props when dropping (and will be receiving support for different models), but that is not a desired feature here.
