### ISSUE TITLE
Create a admin command for open inventory's user

### ISSUE THREAD

**Issue by kevvLove** [thelindat/linden_inventory#88]
Its necessary for any problem o any situation of rol.

**Comment by Borea** [comment]
+rep

**Comment by ScaredDonut** [comment]
Just modify the /steal command

**Comment by FreakOutModz** [comment]
I have propose change by your idea in: https://github.com/thelindat/linden_inventory/pull/108

**Comment by thelindat** [comment]
This will be included with the next update.
