### ISSUE TITLE
stashes without job

### ISSUE THREAD

**Issue by maxcamorra** [thelindat/linden_inventory#9]
At the moment you can only make stashes with a job inside the stashes config.

It would be awesome to have the option to leave out the job field so that everyone can use the stash but have their own inventory in it and not a shared one.

**Comment by thelindat** [comment]
They already work. Do not include the job variable as part of the table.
```lua
{ coords = vector3(301.4374, -599.2748, 43.2821), slots = 71, name = 'Hospital Cloakroom' }
```

![image](https://user-images.githubusercontent.com/65407488/114937419-209c0e00-9e81-11eb-8d11-17d108533a32.png)
