### ISSUE TITLE
Can't open inventory after death revive

### ISSUE THREAD

**Issue by ScaredDonut** [thelindat/linden_inventory#92]
**Describe the bug**
Hey there, so I switched to ESX legacy and basically after playing for a few hours you can't access your inventory after getting revived.

**To Reproduce**
1. start a server
2. join
3. die
4. revive/get revived
5. try to open inventory

**Expected behavior**
The inventory should open after you're alive again.

**Screenshots**
Not much to add really. 

**Additional context**
No errors client side (F8) or server side (Console)

There is a warning however when trying to restart Linden Inv while server is up with people in:

[ script:ghmattimysql] [MySQL] [WARNING] [linden_inventory] [312ms] UPDATE `users` SET `inventory` = ? WHERE identifier = ? : ["[{\"slot\":1,\"count\":1,\"metadata\":{\"serial\":\"LS192114257821\",\"components\":[],\"image\":\"WEAPON_PISTOL\",\"ammo\":1,\"durability\":96.58000000000001,\"registered\":\"Mark Weston\"},\"name\":\"WEAPON_PISTOL\"},{\"slot\":2,\"count\":1,\"metadata\":{\"durability\":97.91,\"image\":\"WEAPON_FLASHLIGHT\"},\"name\":\"WEAPON_FLASHLIGHT\"},{\"slot\":3,\"count\":27,\"name\":\"ammo-9\"},{\"slot\":4,\"count\":1,\"metadata\":{\"image\":\"blue_phone\"},\"name\":\"blue_phone\"},{\"slot\":5,\"count\":131880,\"metadata\":{\"image\":\"money\"},\"name\":\"money\"},{\"slot\":6,\"count\":11,\"name\":\"magnumxlrod\"},{\"slot\":7,\"count\":10,\"name\":\"fishinghookno10\"},{\"slot\":8,\"count\":10,\"name\":\"technoplankton\"},{\"slot\":9,\"count\":10,\"name\":\"kingbraid\"},{\"slot\":10,\"count\":10,\"name\":\"hugecutbait\"},{\"slot\":11,\"count\":2,\"name\":\"zillareel\"},{\"slot\":12,\"count\":2,\"name\":\"water\"},{\"slot\":13,\"count\":1,\"name\":\"trimmers\"},{\"slot\":14,\"count\":6,\"name\":\"cannabis\"},{\"slot\":15,\"count\":4,\"name\":\"marijuana\"},{\"slot\":16,\"count\":2,\"name\":\"drillbit\"},{\"slot\":17,\"count\":28,\"name\":\"iron\"},{\"slot\":18,\"count\":1,\"metadata\":{\"weight\":0,\"bag\":\"WIP1622115465\",\"image\":\"paperbag\"},\"name\":\"paperbag\"},{\"slot\":19,\"count\":2,\"name\":\"ironore\"},{\"slot\":20,\"count\":1,\"metadata\":{\"image\":\"redworms\"},\"name\":\"redworms\"}]","1:steam:11000010495713d"]

**Comment by thelindat** [comment]
> Hey there, so I switched to ESX legacy and basically after playing for a few hours you can't access your inventory after getting revived.


Wait so it works fine after getting revived, until eventually it doesn't? 🤔

**Comment by ScaredDonut** [comment]
Sorry, after you die you cannot access your inventory regardless if you're revive or not. Only a relog will fix it.

**Comment by thelindat** [comment]
Unable to reproduce. Please answer the following

	- What version (or branch) are you using (1.5.x / dev)?
	- If using main, does the issue occur on dev?
	- Are your files modified?
	- Are you using the es_extended import or defining ESX manually?
	- Did you manually edit ESX Legacy or use mine?

Also add a print for `ESX.PlayerData.dead` in a loop somewhere and see what it's printing before dying and after reviving.

**Comment by ScaredDonut** [comment]
1 ) 1.5.4 - Fixed Bags release
2 ) Slightly, the generate serial number to my liking, added AddXP trigger, and uncommented the paperbag stuff, and a custom triggers added to store serial numbers for evidence ssystem. Nothing that should prevent an inventory from opening I think though.
3 ) Sorry, what do you mean?
4 ) Your version, also slightly modified to make Mf-chars work and PayDay system is modified to include logs and transaction logs for banking and a double salary system for double XP events.

Looks like that it still thinks that I am dead after a revive.

**Comment by thelindat** [comment]
These events are part of ESX itself. Ensure your ambulancejob is up to date and triggering this event (it should be doing this by default).
```lua
AddEventHandler('esx:onPlayerSpawn', function()
	local playerPed = PlayerPedId()
	if ESX.PlayerData.ped ~= playerPed then ESX.SetPlayerData('ped', playerPed) end
	ESX.SetPlayerData('dead', false)
end)

AddEventHandler('esx:onPlayerDeath', function()
	local playerPed = PlayerPedId()
	if ESX.PlayerData.ped ~= playerPed then ESX.SetPlayerData('ped', playerPed) end
	ESX.SetPlayerData('dead', true)
end)
```

**Comment by ScaredDonut** [comment]
Thanks mate! That worked. Thank you for your time and help!! ♥

**Comment by thelindat** [comment]
> Thanks mate! That worked. Thank you for your time and help!! ♥

Was ambulance job outdated? And not triggering the event with respawnped?

**Comment by ScaredDonut** [comment]
Yeah it is outdated, that part was missing from the job. I've modified the job too much to replace it though so I added this to the revive function/trigger:

ESX.SetPlayerData('dead', false)

**Comment by thelindat** [comment]
You should be adding the esx:onPlayerSpawned trigger which will trigger more than just the setplayerdata

**Comment by ScaredDonut** [comment]
I'll be sure to add that as well. Thank you!

**Comment by thelindat** [comment]
Just need the trigger event and not SetPlayerData, since ESX will handle
that one for you - else you send the events out twice :)
