### ISSUE TITLE
Housing and Vehicle.

### ISSUE THREAD

**Issue by Austin-R418** [thelindat/linden_inventory#95]
I have been trying to get this to work with housing storage and items saving in the trunk and glovebox but haven’t been able to figure it out. If there is a way to do it could you add it to the installation instructions and if not could you add that option?

**Comment by thelindat** [comment]
Trunks and gloveboxes save by default. If they are not, it is because the plates in `owned_vehicles` have a trailing space. Set Config.TrimPlate to false.

Housing storage requires you to enter a single export line, the contents of which will slightly differ based on the resource you are using.
